"""empty message

Revision ID: 5ce04b4bd81d
Revises: 
Create Date: 2020-07-16 16:50:20.172644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce04b4bd81d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amount',
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('produce_amount', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('machine_id')
    )
    op.create_table('anomaly_type_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=20), nullable=False),
    sa.Column('anomaly_type_code', sa.String(length=20), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_type_code')
    )
    op.create_table('backend_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('part_number', sa.String(length=80), nullable=True),
    sa.Column('demand_amount', sa.Integer(), nullable=True),
    sa.Column('open_num', sa.Integer(), nullable=True),
    sa.Column('revise_amount', sa.Integer(), nullable=True),
    sa.Column('revise_open_num', sa.Integer(), nullable=True),
    sa.Column('scheduled_num', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bad_cause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('inj_part_number', sa.String(length=80), nullable=False),
    sa.Column('bad_name', sa.String(length=80), nullable=False),
    sa.Column('ppm', sa.Integer(), nullable=False),
    sa.Column('pics', sa.Integer(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('improvement', sa.Text(), nullable=False),
    sa.Column('finish_date', sa.String(length=80), nullable=False),
    sa.Column('response', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bad_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bad_name', sa.String(length=20), nullable=False),
    sa.Column('bad_code', sa.String(length=20), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bad_code'),
    sa.UniqueConstraint('bad_name')
    )
    op.create_table('building_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('building', sa.String(length=20), nullable=False),
    sa.Column('machine', sa.String(length=20), nullable=False),
    sa.Column('part_number', sa.String(length=20), nullable=False),
    sa.Column('mold', sa.String(length=20), nullable=True),
    sa.Column('produce_amount', sa.Integer(), nullable=True),
    sa.Column('bad_amount', sa.Integer(), nullable=True),
    sa.Column('bad_percent', sa.Float(), nullable=True),
    sa.Column('bad_ppm', sa.Integer(), nullable=True),
    sa.Column('lost_time', sa.Float(), nullable=True),
    sa.Column('real_cycle_time', sa.Float(), nullable=True),
    sa.Column('record_state', sa.Integer(), nullable=False),
    sa.Column('additional_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mold_id', sa.Integer(), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('dim_name', sa.String(length=80), nullable=True),
    sa.Column('measure_tool', sa.String(length=80), nullable=True),
    sa.Column('upper_limit', sa.Float(), nullable=True),
    sa.Column('lower_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cave_number', sa.Integer(), nullable=False),
    sa.Column('first_part_id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('measure_data', sa.Float(), nullable=True),
    sa.Column('determination', sa.String(length=80), nullable=True),
    sa.Column('ng', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examine_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cave_number', sa.Integer(), nullable=False),
    sa.Column('first_part_id', sa.Integer(), nullable=False),
    sa.Column('examine_1', sa.Integer(), nullable=True),
    sa.Column('examine_2', sa.Integer(), nullable=True),
    sa.Column('examine_3', sa.Integer(), nullable=True),
    sa.Column('examine_4', sa.Integer(), nullable=True),
    sa.Column('examine_5', sa.Integer(), nullable=True),
    sa.Column('examine_6', sa.Integer(), nullable=True),
    sa.Column('examine_7', sa.Integer(), nullable=True),
    sa.Column('examine_8', sa.Integer(), nullable=True),
    sa.Column('examine_9', sa.Integer(), nullable=True),
    sa.Column('examine_10', sa.Integer(), nullable=True),
    sa.Column('examine_11', sa.Integer(), nullable=True),
    sa.Column('examine_12', sa.Integer(), nullable=True),
    sa.Column('examine_13', sa.Integer(), nullable=True),
    sa.Column('examine_14', sa.Integer(), nullable=True),
    sa.Column('examine_15', sa.Integer(), nullable=True),
    sa.Column('examine_16', sa.Integer(), nullable=True),
    sa.Column('examine_17', sa.Integer(), nullable=True),
    sa.Column('examine_18', sa.Integer(), nullable=True),
    sa.Column('examine_19', sa.Integer(), nullable=True),
    sa.Column('determination', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_part_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=False),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=80), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('machine_name', sa.String(length=80), nullable=False),
    sa.Column('mold_id', sa.Integer(), nullable=False),
    sa.Column('mold_number', sa.String(length=80), nullable=False),
    sa.Column('mold_number_f', sa.String(length=80), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_part_number', sa.String(length=80), nullable=True),
    sa.Column('grn_no', sa.String(length=80), nullable=True),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('examine_dependence', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('all_determination', sa.String(length=80), nullable=True),
    sa.Column('dimension_id', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.Column('building', sa.String(length=80), nullable=True),
    sa.Column('dimension_state', sa.Integer(), nullable=True),
    sa.Column('examine_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=80), nullable=True),
    sa.Column('machine_name', sa.String(length=80), nullable=False),
    sa.Column('machine_code', sa.String(length=80), nullable=False),
    sa.Column('machine', sa.String(length=80), nullable=True),
    sa.Column('machine_type', sa.String(length=80), nullable=True),
    sa.Column('machine_tonnage', sa.String(length=80), nullable=True),
    sa.Column('machine_brand', sa.String(length=80), nullable=True),
    sa.Column('machine_no', sa.String(length=80), nullable=True),
    sa.Column('machine_location', sa.String(length=80), nullable=True),
    sa.Column('machine_state', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_code'),
    sa.UniqueConstraint('machine_name')
    )
    op.create_table('material_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_part_number', sa.String(length=80), nullable=False),
    sa.Column('material_type', sa.String(length=80), nullable=True),
    sa.Column('material_spec', sa.String(length=80), nullable=True),
    sa.Column('color_number', sa.String(length=80), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('material_vendor', sa.String(length=80), nullable=True),
    sa.Column('alm_state', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_part_number')
    )
    op.create_table('mold_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mold_number', sa.String(length=80), nullable=False),
    sa.Column('mold_number_f', sa.String(length=80), nullable=False),
    sa.Column('cave_number', sa.Integer(), nullable=False),
    sa.Column('ejection_mode', sa.String(length=80), nullable=True),
    sa.Column('mold_state', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mold_number')
    )
    op.create_table('pn_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=80), nullable=False),
    sa.Column('inj_product_name', sa.String(length=80), nullable=False),
    sa.Column('product_name_en', sa.String(length=80), nullable=False),
    sa.Column('std_produce', sa.Float(), nullable=False),
    sa.Column('std_cycle_time', sa.Float(), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.Column('piece', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('product_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('honhai_pn', sa.String(length=80), nullable=False),
    sa.Column('product_code', sa.String(length=80), nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('honhai_pn'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('sign_table_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('db_table_name', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_table_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('table_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('anomaly_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_name', sa.String(length=20), nullable=False),
    sa.Column('anomaly_code', sa.String(length=20), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_type_id'], ['anomaly_type_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_code')
    )
    op.create_table('bad_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=True),
    sa.Column('bad_id', sa.Integer(), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=False),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('improve', sa.Text(), nullable=True),
    sa.Column('responsible', sa.String(length=20), nullable=True),
    sa.Column('finish_date', sa.DateTime(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bad_id'], ['bad_list.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.Column('available', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['pnlist_id'], ['pn_list.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('building', sa.String(length=20), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('get_amount', sa.Integer(), nullable=False),
    sa.Column('feeding_bucket', sa.Integer(), nullable=False),
    sa.Column('dry_bucket', sa.Integer(), nullable=False),
    sa.Column('material_bucket', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('building', sa.String(length=20), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('demand_weight', sa.Float(), nullable=True),
    sa.Column('remain_weight', sa.Float(), nullable=True),
    sa.Column('dispatch_weight', sa.Float(), nullable=True),
    sa.Column('get_weight', sa.Float(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material_list.id'], ),
    sa.ForeignKeyConstraint(['pnlist_id'], ['pn_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mold_pn_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mold_id', sa.Integer(), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mold_id'], ['mold_list.id'], ),
    sa.ForeignKeyConstraint(['pnlist_id'], ['pn_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pn_material_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pnlist_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_weight', sa.Numeric(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material_list.id'], ),
    sa.ForeignKeyConstraint(['pnlist_id'], ['pn_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produce_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('mold_id', sa.Integer(), nullable=True),
    sa.Column('pnlist_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('product_name', sa.String(length=80), nullable=True),
    sa.Column('produce_order', sa.String(length=80), nullable=True),
    sa.Column('version', sa.String(length=80), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine_list.id'], ),
    sa.ForeignKeyConstraint(['mold_id'], ['mold_list.id'], ),
    sa.ForeignKeyConstraint(['pnlist_id'], ['pn_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_process_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_list_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['table_list_id'], ['sign_table_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomaly_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_report_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('begin_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('lost_time', sa.Float(), nullable=False),
    sa.Column('improve', sa.Text(), nullable=True),
    sa.Column('responsible', sa.String(length=20), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly_list.id'], ),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('table_list_id', sa.Integer(), nullable=True),
    sa.Column('process_name_id', sa.Integer(), nullable=True),
    sa.Column('sign_state', sa.Integer(), nullable=False),
    sa.Column('form_index', sa.String(length=20), nullable=True),
    sa.Column('initiator', sa.String(length=20), nullable=True),
    sa.Column('initiator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['process_name_id'], ['sign_process_list.id'], ),
    sa.ForeignKeyConstraint(['table_list_id'], ['sign_table_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sign_process_list_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_list_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('signer', sa.String(length=20), nullable=False),
    sa.Column('sign_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['process_list_id'], ['sign_process_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signer_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('process_list_detail_id', sa.Integer(), nullable=True),
    sa.Column('signer', sa.String(length=20), nullable=False),
    sa.Column('signer_order', sa.Integer(), nullable=False),
    sa.Column('signer_state', sa.Integer(), nullable=False),
    sa.Column('sign_date', sa.DateTime(), nullable=False),
    sa.Column('flag', sa.Numeric(), nullable=False),
    sa.Column('ps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['sign_event.id'], ),
    sa.ForeignKeyConstraint(['process_list_detail_id'], ['sign_process_list_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signer_state')
    op.drop_table('sign_process_list_detail')
    op.drop_table('sign_event')
    op.drop_table('anomaly_record')
    op.drop_table('sign_process_list')
    op.drop_table('produce_schedule')
    op.drop_table('pn_material_list')
    op.drop_table('mold_pn_association')
    op.drop_table('material_dispatch')
    op.drop_table('material_check')
    op.drop_table('bom')
    op.drop_table('bad_record')
    op.drop_table('anomaly_list')
    op.drop_table('user')
    op.drop_table('sign_table_list')
    op.drop_table('role')
    op.drop_table('product_list')
    op.drop_table('pn_list')
    op.drop_table('mold_list')
    op.drop_table('material_list')
    op.drop_table('machine_list')
    op.drop_table('first_part_record')
    op.drop_table('examine_record')
    op.drop_table('dimension_record')
    op.drop_table('dimension')
    op.drop_table('daily_report')
    op.drop_table('building_list')
    op.drop_table('bad_list')
    op.drop_table('bad_cause')
    op.drop_table('backend_demand')
    op.drop_table('anomaly_type_list')
    op.drop_table('amount')
    # ### end Alembic commands ###
