"""empty message

Revision ID: b867d9fb362b
Revises: f9e0a56ab8c3
Create Date: 2020-07-16 17:02:54.575482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b867d9fb362b'
down_revision = 'f9e0a56ab8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test1')
    # ### end Alembic commands ###
