"""empty message

Revision ID: c5c9eb108846
Revises: b867d9fb362b
Create Date: 2020-07-16 17:03:29.577406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c9eb108846'
down_revision = 'b867d9fb362b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
