"""empty message

Revision ID: d68f45af30bc
Revises: c26ed8c4a290
Create Date: 2020-07-20 10:46:57.936700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68f45af30bc'
down_revision = 'c26ed8c4a290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('chi_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'chi_name')
    # ### end Alembic commands ###
