"""empty message

Revision ID: 2aa25bc3a024
Revises: 4e129ffad7dc
Create Date: 2020-07-20 11:02:28.679570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa25bc3a024'
down_revision = '4e129ffad7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
