"""empty message

Revision ID: 961e78e57377
Revises: c5c9eb108846
Create Date: 2020-07-16 17:07:24.120965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961e78e57377'
down_revision = 'c5c9eb108846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test1')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.create_table('test1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test1_pkey')
    )
    # ### end Alembic commands ###
