"""empty message

Revision ID: f6f1d97f7f87
Revises: 31544a8551c8
Create Date: 2020-07-19 13:31:55.114209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f1d97f7f87'
down_revision = '31544a8551c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=80), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('page_url', sa.String(length=80), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('func_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('func_name'),
    sa.UniqueConstraint('num'),
    sa.UniqueConstraint('page_url'),
    sa.UniqueConstraint('permission'),
    sa.UniqueConstraint('route_name')
    )
    op.add_column('daily_report', sa.Column('machine_id', sa.Integer(), nullable=True))
    op.add_column('daily_report', sa.Column('mold_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_report', 'mold_id')
    op.drop_column('daily_report', 'machine_id')
    op.drop_table('auth_manager')
    # ### end Alembic commands ###
